spring.application.name=currency-conversion
server.port=8100

#spring.config.import=optional:configserver:

#spring.sleuth.sampler.probability=1.0
management.endpoints.web.exposure.include=health,prometheus

spring.cloud.openfeign.client.config.currency-exchange.connectTimeout=3000
spring.cloud.openfeign.client.config.currency-exchange.readTimeout=5000

resilience4j.circuitbreaker.instances.exchange.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.exchange.sliding-window-size=5
resilience4j.circuitbreaker.instances.exchange.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.exchange.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.exchange.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.exchange.permitted-number-of-calls-in-half-open-state=2