services:
  exchange:
    build: ./currency-exchange-service
    image: currency-exchange:local
    ports:
      - "8000:8000"

  conversion:
    build: ./currency-conversion-microservice
    image: currency-conversion:local
    environment:
      CURRENCY_EXCHANGE_URI: http://exchange
    ports:
      - "8100:8100"
    depends_on:
      - exchange

  prometheus:
      image: prom/prometheus
      ports:
        - "127.0.0.1:9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  prometheus_data:
  grafana_data: