apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - image: currency-conversion:local
          imagePullPolicy: IfNotPresent
          name: spring-microservices-currency-conversion-service
          envFrom:
            - configMapRef:
                name: currency-conversion
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8100
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8100
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8100
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              memory: 768Mi
#          env:
#            - name: CURRENCY_EXCHANGE_URI
#              value: http://currency-exchange
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default



